name       : cabextract
version    : 1.6
release    : 1
source     :
    - http://www.cabextract.org.uk/cabextract-1.6.tar.gz : cee661b56555350d26943c5e127fc75dd290b7f75689d5ebc1f04957c4af55fb
license    : GPL-3.0
summary    : cabextract - a program to extract Microsoft Cabinet files.
description: |
    Cabinet (.CAB) files are a form of archive, which Microsoft use to distribute their software, and things like Windows Font Packs. The cabextract program unpacks these files.
    For more information, see http://www.cabextract.org.uk/ or run the command 'cabextract --help'.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
